{{- if .Values.{{SERVICE_NAME}}.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "{{APP_NAME}}.{{SERVICE_NAME}}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.{{SERVICE_NAME}}.service.type }}
  ports:
  - port: {{ .Values.{{SERVICE_NAME}}.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if eq .Values.{{SERVICE_NAME}}.service.type "NodePort" }}
    nodePort: {{ .Values.{{SERVICE_NAME}}.service.nodePort }}
    {{- end }}
  selector:
    {{- include "{{APP_NAME}}.{{SERVICE_NAME}}.selectorLabels" . | nindent 4 }}
{{- end }}
