apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "{{APP_NAME}}.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "{{APP_NAME}}.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
